spring.application.name=obs1

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/obs1
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.properties.jakarta.persistence.validation.mode=none

# JWT Configurations
security.jwt.token.secret-key=secureKeyForObsProjectMustBeVeryLongAndSecure123456789InDevMode
security.jwt.token.expire-length=86400000

# Güvenlik Loglaması
logging.level.org.springframework.security=DEBUG 