spring.application.name=obs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/obs
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.properties.jakarta.persistence.validation.mode=none